import React from 'react'
import type { Metadata } from 'next'
import { NavigationMenuHome } from '@/components/NavigationMenu'
import AvatarComponent from '@/components/Avatar'
import { ModeToggle } from '@/components/toggleTheme'

export const metadata: Metadata = {
	title: 'Bank Opole home',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<div className='flex flex-col min-h-screen'>
			<header className="h-16 px-4 flex justify-between border-b shadow-md">
				<div className="flex items-center">
					<ModeToggle />
					<NavigationMenuHome />
				</div>
				<AvatarComponent />
			</header>
			<div className='flex-grow p-8 mt-8 mx-8 text-center'>
				{children}
			</div>
			<footer className='dark:text-white h-16 flex justify-center items-center'>
				<span>
					Matt Patt Design ©2023 Created by Matt5246
				</span>
			</footer>
		</div>
	)
}
