import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StoreProvider from '../StoreProvider'
import { NavigationMenuHome } from '@/components/NavigationMenu'
import AvatarComponent from '@/components/Avatar'

export const metadata: Metadata = {
    title: 'Bank Opole home',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <main className='bg-zinc-100 dark:bg-zinc-900 h-screen'>
            <div className="flex justify-between h-16 px-4 items-center border-b">
                <NavigationMenuHome />
                <AvatarComponent />
            </div>

            <div className='rounded-xl shadow-md p-8 dark:bg-zinc-800 bg-white mt-8 mx-8'>
                <StoreProvider>{children}</StoreProvider>
            </div>
            <footer className='dark:bg-zinc-800 dark:text-white absolute inset-x-0 bottom-0 h-16 flex justify-center items-center'>
                <span>
                    Matt Patt Design ©2023 Created by Matt5246
                </span>
            </footer>
        </main>
    )
}
