import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StoreProvider from '../StoreProvider'
import { NavigationMenuHome } from '@/components/NavigationMenu'
import {
    Avatar,
    AvatarFallback,
    AvatarImage,
} from "@/components/ui/avatar"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Bank Opole home',
    description: 'Generated by create next app',
}
// const items1 = [
//     { label: 'BankOpole', key: '1', href: '/home' },
//     { label: 'My accounts & Transactions', key: '2', href: '/home/transactions' },
//     { label: 'Payments & Transfers', key: '3', href: '/home/transfers' },
//     { label: 'Credit Cards', key: '4', href: '/home/credit-cards' },
//     { label: 'Account Services', key: '5', href: '/home/services' },
// ];

// const items2 = [
//     {
//         label: 'Account',
//         key: 'account',
//         icon: <UserOutlined />,
//     },
//     {
//         label: 'Settings',
//         key: 'settings',
//         href: '/settings',
//     },
//     {
//         label: 'Logout',
//         key: 'logout',
//         href: '/sign-in',
//     },
// ];

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <main className='bg-gray-100 dark:bg-gray-800 h-screen'>
            <div className="flex h-16 px-4 items-center border-b">
                <NavigationMenuHome />
                <Avatar className='flex justify-end'>
                    <AvatarImage src="https://github.com/shadcn.png" alt="@shadcn" />
                    <AvatarFallback>CN</AvatarFallback>
                </Avatar>
            </div>

            <div className='rounded-xl shadow-md p-8 dark:bg-gray-700 bg-white mt-8 mx-8'>
                <StoreProvider>{children}</StoreProvider>
            </div>
            <footer className='dark:bg-gray-800 dark:text-white absolute inset-x-0 bottom-0 h-16' style={{ textAlign: 'center' }}>
                Matt Patt Design ©2023 Created by Matt5246
            </footer>
        </main>
    )
}
